import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
        paddingTop: 30,
        paddingHorizontal: 5,
        textAlign: "center",
    },
    navbar: {
        marginHorizontal: 5,
        marginBottom: 10,
        flexDirection: "row",
        alignContent: "center",
        textAlign: "center",
        alignItems: "center",
        alignSelf: "center",
    },
    icon: {
        tintColor: "#fff",
        width: 25,
        height: 25,
        alignContent: "center",
        marginHorizontal: 22,
        marginVertical: 15,
        alignItems: 'center',
    },
    apple: {
        position: "absolute",
        left: 85,
        top: 17,
        tintColor: "#000",
        width: 18,
        height: 18,
    },
    eye: {
        tintColor: "#fff",
        width: 25,
        height: 25,
        alignContent: "flex-end",
        alignItems: "flex-end",
        position: "absolute",
        right: 10,
        marginTop: 15,
    },
    iconPhoto: {
        borderRadius: 50,
        width: 25,
        height: 25,
        alignContent: "center",
        marginHorizontal: 22,
        marginVertical: 15,
    },
    title: {
        alignContent: "center",
        textAlign: "center",
        color: '#fff',
        marginHorizontal: 10,
        fontSize: 16,
        fontWeight: 'bold'
    },
    loginTitle: {
        color: '#fff',
        marginHorizontal: 98,
        fontWeight: 'bold',
        fontSize: 20,
        alignContent: "center",
        textAlign: "center",
        alignItems: "center",
        alignSelf: "center",
    },
    desc: {
        color: '#fff',
        marginHorizontal: 5,
        marginVertical: 5,
        textAlign: "left",
        alignContent: "flex-start",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        alignSelf: "flex-start",
    },
    loginDesc: {
        color: '#fff',
        marginHorizontal: 5,
        marginTop: 20,
        textAlign: "left",
        fontSize: 18,
    },
    loginEnd: {
        color: '#fff',
        marginHorizontal: 5,
        marginTop: 20,
        textAlign: "center",
        fontSize: 18,
        fontWeight: "bold",
    },
    image: {
        width: "100%",
        padding: 4,
        maxHeight: 300,
        borderRadius: 12,
        marginLeft: 4,
        flexBasis: '96%',
    },
    division: {
        flexBasis: '50%',
        flexDirection: "row",
    },
    header: {
        marginTop: 5,
        flexDirection: "row",
        textAlign: "center",
        alignSelf: "center",
    },
    loginHeader: {
        flex: -1,
        marginHorizontal: 5,
        flexDirection: "row",
        alignItems: "flex-start",
        alignSelf: "flex-start",
    },
    photos: {
        flexDirection: 'row',
    },
    button: {
        backgroundColor: '#444',
        padding: 15,
        borderRadius: 50,
        alignItems: 'center',
        marginVertical: 5,
        width: "100%",
    },
    center: {
        alignContent: "center",
        textAlign: "center",
        alignItems: "center",
        alignSelf: "center",
    },
    textButton: {
        marginLeft: 5,
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        alignContent: "center",
        textAlign: "center",
        alignItems: "center",
        alignSelf: "center",
    },
    input: {
        backgroundColor: '#000',
        color: '#fff',
        fontSize: 24,
        fontWeight: "bold",
        padding: Platform.OS === 'ios' ? 15 : 10,
        borderRadius: 7
    },
});

export default styles